version: "3"
services:
  saml:
    environment:
      - DJANGO_ENV
      - DJANGO_SECRET_KEY
      - SAML_KEY
      - SAML_URL
      - SITE_URL
    image: "aswwu/saml:${DJANGO_TAG}"
    build: .
    container_name: aswwu_saml
    volumes:
      - "${SAML_DIR}:/home/django/django_server/saml"
    restart: always
    ports:
      - "${DJANGO_PORT}:8000"
  # db:
  #   image: mariadb:10.8
  #   container_name: aswwu_db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD
  #     - MYSQL_DATABASE
  #     - MYSQL_USER
  #     - MYSQL_PASSWORD
  #   volumes:
  #     - "${DB_DIR}:/var/lib/mysql"
  #   restart: always
